/**
 * Dashboard.tsx — Main dashboard page.
 *
 * Uses WebSocket for real-time twin state updates.
 * Caches last valid values to prevent N/A flicker during connection
 * transitions (e.g., when ESP8266 sends a reading every 5s).
 */

import { useEffect, useRef, useState } from 'react';
import { useWebSocket } from '../hooks/useWebSocket';
import { twinApi } from '../services/api';
import type { TwinState } from '../types';

// ─────────────────────────────────────────────────────────────
// Data source badge helper
// ─────────────────────────────────────────────────────────────

function getSourceBadge(ds: string | undefined, connected: boolean) {
  if (!connected) {
    return { label: '⚠ BACKEND OFFLINE', color: '#ef4444', bg: 'rgba(239,68,68,0.12)', border: 'rgba(239,68,68,0.3)' };
  }
  switch (ds) {
    case 'LIVE':
    case 'ESP8266':
      return { label: '⚡ LIVE — ESP8266 HARDWARE', color: '#00e599', bg: 'rgba(0,229,153,0.1)', border: 'rgba(0,229,153,0.35)' };
    case 'SIMULATION':
      return { label: '🔷 SIMULATION MODE', color: '#38bdf8', bg: 'rgba(56,189,248,0.1)', border: 'rgba(56,189,248,0.3)' };
    case 'STALE':
      return { label: '⏳ ESP8266 STALE — Signal lost', color: '#f59e0b', bg: 'rgba(245,158,11,0.1)', border: 'rgba(245,158,11,0.3)' };
    case 'WAITING':
    default:
      return { label: '⏳ WAITING FOR ESP8266 DATA', color: '#94a3b8', bg: 'rgba(148,163,184,0.08)', border: 'rgba(148,163,184,0.2)' };
  }
}

// ─────────────────────────────────────────────────────────────
// Helper: safe format
// ─────────────────────────────────────────────────────────────

const fmt = (v: number | null | undefined, suffix = '') =>
  v !== null && v !== undefined ? `${v}${suffix}` : 'N/A';

// ─────────────────────────────────────────────────────────────
// Dashboard Component
// ─────────────────────────────────────────────────────────────

interface DashboardProps {
  twinState?: TwinState | null;
  connected?: boolean;
}

export function Dashboard({ twinState: propTwin, connected: propConnected }: DashboardProps = {}) {
  // If props are passed from App, use them; otherwise hook into WebSocket
  const ws = useWebSocket();
  const activeTwin = propTwin !== undefined ? propTwin : ws.twinState;
  const connected = propConnected !== undefined ? propConnected : ws.connected;

  // Cached twin — preserves last known good values so the display
  // doesn't blank out between readings (prevents N/A flicker)
  const cachedTwin = useRef<TwinState | null>(activeTwin || null);
  const [displayTwin, setDisplayTwin] = useState<TwinState | null>(activeTwin || null);

  // 1. Initial HTTP fetch on mount so data is displayed immediately in < 200ms
  useEffect(() => {
    let active = true;
    twinApi.getState()
      .then((state) => {
        if (active && state) {
          cachedTwin.current = state;
          setDisplayTwin((prev) => (prev !== null ? prev : state));
        }
      })
      .catch((err) => console.warn('Dashboard initial fetch error:', err));
    return () => {
      active = false;
    };
  }, []);

  // 2. Sync whenever WebSocket or parent prop updates
  useEffect(() => {
    if (activeTwin) {
      cachedTwin.current = activeTwin;
      setDisplayTwin(activeTwin);
    }
  }, [activeTwin]);

  const ts = displayTwin;

  const temperature = ts?.temperature;
  const humidity = ts?.humidity;
  const mq5 = ts?.mq5;
  const mq2 = ts?.mq2;
  const healthScore = ts?.health_score ?? 100;
  const status = ts?.status ?? 'HEALTHY';
  const dataSource = ts?.data_source;

  const mq2Status = mq2 === 1 ? 'ALERT' : 'NORMAL';

  const lastUpdated = ts?.last_update
    ? new Date(ts.last_update).toLocaleTimeString()
    : 'Waiting...';

  const badge = getSourceBadge(dataSource, connected);

  const isSimulation = dataSource === 'SIMULATION';

  return (
    <div className="dashboard-page">

      {/* Header information */}
      <div className="dashboard-heading">
        <div>
          <h1>Biogas Plant Dashboard</h1>
          <p>Real-time monitoring and digital twin visualization</p>
        </div>

        <div className="dashboard-status" style={{
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          background: badge.bg, border: `1px solid ${badge.border}`,
          color: badge.color, borderRadius: 8, padding: '0.3rem 0.8rem',
          fontSize: '0.75rem', fontWeight: 700
        }}>
          {badge.label}
        </div>
      </div>

      {/* Simulation warning banner */}
      {isSimulation && (
        <div style={{
          background: 'rgba(56,189,248,0.08)', border: '1px solid rgba(56,189,248,0.25)',
          color: '#38bdf8', borderRadius: 8, padding: '0.6rem 1rem',
          fontSize: '0.8rem', fontWeight: 600, margin: '0 0 1rem 0'
        }}>
          🔷 SIMULATION MODE ACTIVE — All readings are generated by the simulation engine.
          These are <strong>not</strong> real sensor measurements.
          Click &quot;Stop Simulation&quot; in the header to return to live hardware mode.
        </div>
      )}

      <div className="dashboard-grid">

        {/* ===================================================== */}
        {/* DIGITAL TWIN VIRTUAL PLANT                           */}
        {/* ===================================================== */}

        <section className="digital-twin-card">

          <div className="digital-twin-title">
            <h2>DIGITAL TWIN - VIRTUAL PLANT</h2>
            <p>
              {!connected
                ? 'Backend offline — reconnecting...'
                : dataSource === 'LIVE' || dataSource === 'ESP8266'
                ? 'Synchronized with physical plant (ESP8266)'
                : dataSource === 'SIMULATION'
                ? 'Running on simulation data'
                : dataSource === 'STALE'
                ? 'ESP8266 signal lost — displaying last known values'
                : 'Waiting for ESP8266 connection...'}
            </p>
          </div>

          {/* Virtual plant illustration */}
          <div className="virtual-plant">

            <div className="sky-glow"></div>

            <div className="plant-label">
              BIOGAS DIGESTER
            </div>

            {/* Digester dome */}
            <div className="digester-dome">
              <div className="dome-highlight"></div>
            </div>

            {/* Digester body */}
            <div className="digester-body">
              <div className="digester-window">
                <div className="slurry"></div>
                <div className="pipe pipe-one"></div>
                <div className="pipe pipe-two"></div>
              </div>
            </div>

            {/* Gas holder */}
            <div className="gas-holder">
              <div className="gas-holder-dome"></div>
              <div className="gas-holder-base"></div>
            </div>

            {/* Connecting pipes */}
            <div className="plant-pipe pipe-left"></div>
            <div className="plant-pipe pipe-right"></div>
            <div className="plant-pipe pipe-bottom"></div>

            {/* Feed tank */}
            <div className="feed-tank">
              <div className="tank-top"></div>
              <div className="tank-body"></div>
            </div>

            {/* Slurry outlet */}
            <div className="slurry-tank">
              <div className="tank-top"></div>
              <div className="tank-body"></div>
            </div>

            {/* Plant ground */}
            <div className="plant-ground"></div>

            {/* Information labels */}
            <div className="plant-info gas-holder-info">
              <span>GAS HOLDER</span>
              <strong>Pressure: Estimated</strong>
              <small>No pressure sensor connected</small>
            </div>

            <div className="plant-info digester-info">
              <span>DIGESTER</span>
              <strong>
                Temperature: {fmt(temperature, ' °C')}
              </strong>
              <small>
                {isSimulation ? 'Simulation estimate' : 'Live ESP8266 measurement'}
              </small>
            </div>

            <div className="plant-info outlet-info">
              <span>GAS OUTLET ➜</span>
              <strong>Flow rate: Estimated</strong>
              <small>Flow sensor not connected</small>
            </div>

            <div className="plant-info feed-info">
              <span>INLET FEED TANK</span>
              <strong>Level: Estimated</strong>
              <small>Digital Twin value</small>
            </div>

            <div className="plant-info slurry-info">
              <span>SLURRY OUTLET</span>
              <strong>Level: Estimated</strong>
              <small>Digital Twin value</small>
            </div>

          </div>
        </section>

        {/* ===================================================== */}
        {/* LIVE SENSOR DATA                                      */}
        {/* ===================================================== */}

        <section className="sensor-card">
          <div className="section-title">
            <h2>
              {isSimulation ? 'SIMULATED SENSOR DATA' : 'LIVE SENSOR DATA'}
            </h2>
            <span
              className="live-badge"
              style={isSimulation ? { background: 'rgba(56,189,248,0.15)', color: '#38bdf8', border: '1px solid rgba(56,189,248,0.3)' } : {}}
            >
              {dataSource === 'LIVE' || dataSource === 'ESP8266'
                ? 'LIVE'
                : dataSource === 'SIMULATION'
                ? 'SIM'
                : dataSource === 'STALE'
                ? 'STALE'
                : 'WAITING'}
            </span>
          </div>

          <div className="sensor-grid">

            <SensorBox
              title="Methane (CH₄)"
              value={fmt(ts?.methane_estimate, ' %')}
              subtitle={isSimulation ? 'Simulation estimate' : 'Digital Twin estimate (no CH₄ sensor)'}
              estimated={!isSimulation}
            />

            <SensorBox
              title="Carbon Dioxide (CO₂)"
              value="N/A"
              subtitle="No CO₂ sensor connected"
            />

            <SensorBox
              title="Temperature — DHT11"
              value={fmt(temperature, ' °C')}
              subtitle={isSimulation ? 'Simulation estimate' : 'Real ESP8266 measurement'}
              live={!isSimulation}
            />

            <SensorBox
              title="Pressure"
              value="N/A"
              subtitle="No pressure sensor connected"
            />

            <SensorBox
              title="MQ-5 Relative Gas Level"
              value={fmt(mq5)}
              subtitle="Raw analog value — not calibrated ppm"
              live={!isSimulation}
            />

            <SensorBox
              title="Humidity — DHT11"
              value={fmt(humidity, ' %RH')}
              subtitle={isSimulation ? 'Simulation estimate' : 'Real ESP8266 measurement'}
              live={!isSimulation}
            />

            <SensorBox
              title="MQ-2 Gas Detection"
              value={mq2 !== null && mq2 !== undefined ? mq2Status : 'N/A'}
              subtitle="Digital threshold detection"
              alert={mq2Status === 'ALERT'}
              live={!isSimulation}
            />

            <SensorBox
              title="H₂S — Hydrogen Sulfide"
              value="N/A"
              subtitle="No H₂S sensor connected"
            />

          </div>

          <div className="data-source">
            Data source:
            <strong style={{ color: badge.color }}>
              {' '}{dataSource || 'WAITING'}
            </strong>
          </div>

          <div className="last-updated">
            Last updated: {lastUpdated}
          </div>
        </section>

      </div>

      {/* ===================================================== */}
      {/* LOWER DASHBOARD CARDS                                */}
      {/* ===================================================== */}

      <div className="lower-grid">

        {/* Plant health */}
        <section className="health-card">
          <h2>PLANT HEALTH INDEX</h2>

          <div className="health-content">
            <div className="health-circle">
              <strong>{Math.round(healthScore)}</strong>
              <span>/100</span>
            </div>

            <div className="health-details">
              <h3
                style={{
                  color: status === 'HEALTHY'
                    ? '#00e599'
                    : status === 'DEGRADING'
                    ? '#f59e0b'
                    : '#ef4444'
                }}
              >
                {status}
              </h3>
              <p>
                Health status calculated from available monitoring
                parameters.
                {isSimulation && ' (Simulation data)'}
              </p>

              {ts?.anomaly_detected && (
                <div style={{
                  background: 'rgba(239,68,68,0.1)',
                  border: '1px solid rgba(239,68,68,0.3)',
                  color: '#ef4444',
                  borderRadius: 6,
                  padding: '0.4rem 0.6rem',
                  fontSize: '0.75rem',
                  fontWeight: 600,
                  marginTop: '0.5rem'
                }}>
                  ⚠ Anomaly: {ts.anomaly_reason || 'Detected'}
                </div>
              )}

              <div className="health-row">
                <span>Health Score</span>
                <strong>{Math.round(healthScore)}%</strong>
              </div>

              <div className="health-row">
                <span>Anomaly</span>
                <strong style={{ color: ts?.anomaly_detected ? '#ef4444' : '#00e599' }}>
                  {ts?.anomaly_detected ? 'DETECTED' : 'NONE'}
                </strong>
              </div>

              <div className="health-row">
                <span>Connection</span>
                <strong style={{ color: badge.color }}>
                  {ts?.connection_status || dataSource || 'WAITING'}
                </strong>
              </div>
            </div>
          </div>
        </section>

        {/* Real-time trends */}
        <section className="trend-card">
          <h2>REAL-TIME TRENDS</h2>

          <div className="trend-legend">
            <span className="legend-methane">● CH₄ Estimate</span>
            <span className="legend-temperature">● Temperature</span>
          </div>

          <div className="simple-chart">
            <div className="chart-y-axis">
              <span>100</span>
              <span>75</span>
              <span>50</span>
              <span>25</span>
              <span>0</span>
            </div>

            <div className="chart-area">
              <div className="chart-line methane-line"></div>
              <div className="chart-line temperature-line"></div>

              <div className="chart-grid-line line-1"></div>
              <div className="chart-grid-line line-2"></div>
              <div className="chart-grid-line line-3"></div>
              <div className="chart-grid-line line-4"></div>
            </div>
          </div>

          <div className="chart-time">
            <span>Now</span>
            <span>+5 min</span>
            <span>+10 min</span>
            <span>+15 min</span>
          </div>
        </section>

        {/* Prediction */}
        <section className="prediction-card">
          <h2>PREDICTION — NEXT 6 HOURS</h2>

          <div className="prediction-grid">

            <PredictionBox
              title="Methane Estimate"
              value={ts?.temp_prediction?.predicted_value != null
                ? `${ts.temp_prediction.predicted_value.toFixed(1)} %`
                : 'N/A'}
              status={ts?.temp_prediction?.trend || 'Estimated'}
            />

            <PredictionBox
              title="Gas Flow Estimate"
              value="N/A"
              status="No flow sensor"
            />

            <PredictionBox
              title="Pressure"
              value="N/A"
              status="No sensor"
            />

            <PredictionBox
              title="Current Temperature"
              value={fmt(temperature, ' °C')}
              status={isSimulation ? 'Simulation' : 'Live'}
            />

          </div>
        </section>

      </div>

    </div>
  );
}

/* ========================================================= */
/* SENSOR BOX COMPONENT                                      */
/* ========================================================= */

interface SensorBoxProps {
  title: string;
  value: string;
  subtitle: string;
  estimated?: boolean;
  live?: boolean;
  alert?: boolean;
}

function SensorBox({
  title,
  value,
  subtitle,
  estimated,
  live,
  alert,
}: SensorBoxProps) {
  return (
    <div className="sensor-box">
      <div className="sensor-title">{title}</div>

      <div
        className={`sensor-value ${alert ? 'value-alert' : ''
          } ${estimated ? 'value-estimated' : ''}`}
      >
        {value}
      </div>

      <div
        className={`sensor-subtitle ${live ? 'subtitle-live' : ''
          }`}
      >
        {subtitle}
      </div>
    </div>
  );
}

/* ========================================================= */
/* PREDICTION BOX COMPONENT                                  */
/* ========================================================= */

interface PredictionBoxProps {
  title: string;
  value: string;
  status: string;
}

function PredictionBox({
  title,
  value,
  status,
}: PredictionBoxProps) {
  return (
    <div className="prediction-box">
      <span>{title}</span>
      <strong>{value}</strong>
      <small>{status}</small>

      <div className="prediction-line">
        <span></span>
      </div>
    </div>
  );
}