// pages/SensorsPage.tsx — Live sensor data display
import React from 'react';
import type { TwinState } from '../types';

interface Props { twinState: TwinState | null; }

const Gauge = ({ value, min, max, label, unit, color }: { value: number|null; min: number; max: number; label: string; unit: string; color: string }) => {
  const pct = value != null ? Math.min(100, Math.max(0, ((value - min) / (max - min)) * 100)) : 0;
  return (
    <div style={{ textAlign: 'center' }}>
      <svg viewBox="0 0 120 70" style={{ width: 150, overflow: 'visible' }}>
        {/* Track arc */}
        <path d="M 10 65 A 50 50 0 0 1 110 65" fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="12" strokeLinecap="round"/>
        {/* Value arc */}
        <path d={`M 10 65 A 50 50 0 0 1 110 65`} fill="none" stroke={color} strokeWidth="12" strokeLinecap="round"
          strokeDasharray={`${pct * 1.57} 157`}/>
        {/* Value text */}
        <text x="60" y="62" textAnchor="middle" fill={color} fontSize="14" fontWeight="800">
          {value != null ? value.toFixed(value > 100 ? 0 : 1) : '—'}
        </text>
        <text x="60" y="74" textAnchor="middle" fill="#64748b" fontSize="9">
          {unit}
        </text>
      </svg>
      <div style={{ fontSize: '0.7rem', color: '#64748b', fontWeight: 600, letterSpacing: '0.06em', marginTop: '0.25rem' }}>
        {label}
      </div>
    </div>
  );
};

export const SensorsPage: React.FC<Props> = ({ twinState: ts }) => {
  return (
    <div style={{ padding: '1.5rem', maxWidth: 1100, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <h1 style={{ fontSize: '1.4rem', fontWeight: 800 }}><span className="gradient-text">Live Sensors</span></h1>

      {ts?.data_source === 'SIMULATION' && (
        <div className="sim-banner">
          🔷 SIMULATION MODE — All readings generated by simulation engine. Not real sensor measurements.
        </div>
      )}

      {/* Source badge */}
      <div className="card" style={{ textAlign: 'center' }}>
        <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', letterSpacing: '0.08em', marginBottom: '0.75rem' }}>
          ▸ DATA SOURCE
        </div>
        <div className={`status-badge ${ts?.data_source === 'ESP8266' ? 'badge-healthy' : 'badge-sim'}`}
          style={{ fontSize: '0.9rem', padding: '0.5rem 1.5rem' }}>
          {ts?.data_source === 'ESP8266' ? '⚡ LIVE ESP8266 HARDWARE' : '🔷 SIMULATION ENGINE'}
        </div>
        {ts?.last_update && (
          <div style={{ fontSize: '0.72rem', color: '#475569', marginTop: '0.5rem' }}>
            Last update: {new Date(ts.last_update).toLocaleString()}
          </div>
        )}
      </div>

      {/* Gauges */}
      <div className="card">
        <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', letterSpacing: '0.08em', marginBottom: '1rem' }}>
          ▸ SENSOR GAUGES
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-around', flexWrap: 'wrap', gap: '1.5rem' }}>
          <Gauge value={ts?.temperature ?? null} min={10} max={50} label="TEMPERATURE (DHT11)" unit="°C" color="#3b82f6"/>
          <Gauge value={ts?.humidity ?? null} min={0} max={100} label="HUMIDITY (DHT11)" unit="%" color="#06b6d4"/>
          <Gauge value={ts?.mq5 ?? null} min={0} max={1024} label="MQ-5 GAS INDICATOR" unit="ADC" color="#f59e0b"/>
          <Gauge value={ts?.mq2 ?? null} min={0} max={1024} label="MQ-2 GAS/SMOKE INDICATOR" unit="ADC" color="#8b5cf6"/>
          <Gauge value={ts?.methane_estimate ?? null} min={0} max={100} label="CH₄ ESTIMATE [SIM]" unit="%" color="#f97316"/>
          <Gauge value={ts?.gas_production ?? null} min={0} max={4} label="GAS PROD [SIM]" unit="L/min" color="#00c896"/>
        </div>
      </div>

      {/* Raw values table */}
      <div className="card">
        <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', letterSpacing: '0.08em', marginBottom: '0.75rem' }}>
          ▸ RAW SENSOR VALUES
        </div>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
              {['Parameter', 'Value', 'Unit', 'Source', 'Note'].map(h => (
                <th key={h} style={{ textAlign: 'left', padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 600, fontSize: '0.7rem', letterSpacing: '0.05em' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[
              { param: 'Temperature', value: ts?.temperature?.toFixed(2), unit: '°C', source: ts?.data_source ?? '—', note: 'DHT11 sensor (real when ESP8266 connected)' },
              { param: 'Humidity', value: ts?.humidity?.toFixed(2), unit: '%', source: ts?.data_source ?? '—', note: 'DHT11 sensor (real when ESP8266 connected)' },
              { param: 'MQ-5 Reading', value: ts?.mq5?.toFixed(0), unit: 'ADC units', source: ts?.data_source ?? '—', note: 'Relative gas indicator (NOT calibrated ppm)' },
              { param: 'MQ-2 Reading', value: ts?.mq2?.toFixed(0), unit: 'ADC units', source: ts?.data_source ?? '—', note: 'Relative gas/smoke indicator (NOT calibrated ppm)' },
              { param: 'Methane Estimate', value: ts?.methane_estimate?.toFixed(2), unit: '%', source: 'SIMULATION', note: '⚠ SIMULATION ESTIMATE — not a real measurement' },
              { param: 'Gas Production', value: ts?.gas_production?.toFixed(3), unit: 'L/min', source: 'SIMULATION', note: '⚠ SIMULATION ESTIMATE — not a real measurement' },
            ].map(row => (
              <tr key={row.param} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                <td style={{ padding: '0.55rem 0.75rem', fontWeight: 600, color: '#e2e8f0' }}>{row.param}</td>
                <td style={{ padding: '0.55rem 0.75rem', color: '#00c896', fontWeight: 700, fontVariantNumeric: 'tabular-nums' }}>{row.value ?? '—'}</td>
                <td style={{ padding: '0.55rem 0.75rem', color: '#64748b' }}>{row.unit}</td>
                <td style={{ padding: '0.55rem 0.75rem' }}>
                  <span className={`status-badge ${row.source === 'ESP8266' ? 'badge-healthy' : 'badge-sim'}`} style={{ fontSize: '0.6rem' }}>
                    {row.source}
                  </span>
                </td>
                <td style={{ padding: '0.55rem 0.75rem', color: '#475569', fontSize: '0.72rem' }}>{row.note}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
