"""
models.py — SQLAlchemy ORM models (database table definitions).
"""

from sqlalchemy import Column, Integer, Float, String, Boolean, DateTime, Text
from sqlalchemy.sql import func
from app.database.database import Base


class SensorReading(Base):
    """
    Stores every sensor reading — from ESP8266 hardware OR simulation.
    The 'source' field identifies whether the reading is real or simulated.
    """
    __tablename__ = "sensor_readings"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False, index=True)
    device_id = Column(String(50), default="digester01", nullable=False)

    # Real sensor values (available from DHT11 and MQ sensors on ESP8266)
    temperature = Column(Float, nullable=True)       # °C from DHT11
    humidity = Column(Float, nullable=True)           # % from DHT11
    mq5_value = Column(Float, nullable=True)          # Raw ADC value from MQ-5
    mq2_value = Column(Float, nullable=True)          # Raw ADC value from MQ-2

    # Simulated / estimated process variables
    # NOTE: These are NOT real measurements unless calibrated hardware is used
    methane_simulated = Column(Float, nullable=True)       # Estimated % — SIMULATION
    gas_production_simulated = Column(Float, nullable=True) # Estimated L/min — SIMULATION

    # Source: "SIMULATION" or "ESP8266"
    source = Column(String(20), default="SIMULATION", nullable=False)


class DigitalTwinState(Base):
    """
    Stores snapshots of the Digital Twin state at each update.
    The Digital Twin is a virtual model synchronized with sensor data.
    """
    __tablename__ = "digital_twin_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False, index=True)

    # Current state values (mirrored from latest sensor reading)
    temperature = Column(Float, nullable=True)
    humidity = Column(Float, nullable=True)
    gas_indicator = Column(Float, nullable=True)    # Combined MQ indicator
    methane_estimate = Column(Float, nullable=True)  # Simulated methane %
    gas_production = Column(Float, nullable=True)    # Simulated gas L/min

    # Health and status
    health_score = Column(Float, nullable=True)      # 0–100
    status = Column(String(20), default="HEALTHY")   # HEALTHY / DEGRADING / CRITICAL

    # Anomaly information
    anomaly_detected = Column(Boolean, default=False)
    anomaly_reason = Column(Text, nullable=True)     # Human-readable reason

    # Source of data feeding this twin state
    data_source = Column(String(20), default="SIMULATION")


class Prediction(Base):
    """
    Stores model predictions for gas production and other parameters.
    All predictions based on simulation data are clearly labeled.
    """
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False, index=True)
    prediction_horizon = Column(String(20), nullable=True)  # e.g., "1h", "6h"
    parameter = Column(String(50), nullable=True)            # e.g., "gas_production"
    predicted_value = Column(Float, nullable=True)
    confidence = Column(Float, nullable=True)                # R² or similar
    model_type = Column(String(50), nullable=True)           # e.g., "LinearRegression"
    based_on = Column(String(20), default="SIMULATION")      # Data source


class SimulationRun(Base):
    """
    Stores records of simulation runs, including What-If scenarios.
    """
    __tablename__ = "simulation_runs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False)
    scenario_name = Column(String(100), nullable=True)
    input_parameters = Column(Text, nullable=True)   # JSON string of inputs
    predicted_outputs = Column(Text, nullable=True)  # JSON string of outputs
    duration_hours = Column(Float, nullable=True)


class Alert(Base):
    """Stores alert events generated by the system."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False, index=True)
    level = Column(String(20), default="INFO")   # INFO / WARNING / CRITICAL
    message = Column(Text, nullable=True)
    parameter = Column(String(50), nullable=True)
    value = Column(Float, nullable=True)
    acknowledged = Column(Boolean, default=False)
